[project]
name = "rag-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=0.6.3",
    "ollama>=0.4.7",
    "pymongo>=4.11.3",
    "sanic>=24.12.0",
]
